test:
  - any: ['./client/src/**/*.spec.js', './server/**/*.test.js']
frontend:
  - any: ['./client/src/**/*.*']
backend:
  - any: ['./server/src/**/*.*']
documentation:
  - any: ['./server/**.md']
  
